title: ゆたんぽすと
description: > # this means to ignore newlines until "baseurl:"
  Blog with theme Future Imperfect<br>
baseurl: "/blog.github.io" # the subpath of your site, e.g. /blog
url: "https://yutanpo1227.github.io" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'yutanpo1227'
  last_name: 'yutanpo'
  cv: '//kaptn.ru'
  avatar: '/images/avatar.jpeg'
  github_username:  yutanpo1227
  email: komazawayuu1227@icloud.com
  vk_id: id201664979
  telegram_name: ゆたんぽすと
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


