title: YutanPost
description: > # this means to ignore newlines until "baseurl:"
  情報系大学生のしがないブログです。<br>
  主にソフトやハードの開発日記を中心にアップしようと思っています。<br>
baseurl: "/blog.github.io" # the subpath of your site, e.g. /blog
url: "https://github.com/yutanpo1227" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'yutanpo1227'
  last_name: 'yutanpo'
  cv: 'https://twitter.com/yuu_gakusei'
  avatar: '/images/avatar.jpeg'
  github_username:  yutanpo1227
  email: komazawayuu1227@icloud.com
  vk_id: id0000000
  telegram_name: ゆたんぽすと
  logo: '/images/logo.svg'

highlighter: rouge

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:categories/:year/:title.html


